# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    region         = "us-east-2"
    dynamodb_table = "tf-state-790387652718"
    bucket         = "tf-state-790387652718-main"
    key            = "live/prod/aws/us-east-2/state/terraform.tfstate"
    encrypt        = true
  }
}
