name: Terragrunt Test
on:
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo $secret | wc
        id: hm
        env:
          secret: |
            {
              "TF_VAR_GITHUB_ORGANIZATION": "${{ github.repository_owner }}",
              "TF_VAR_APP_ID": "${{ secrets.TF_VAR_APP_ID }}",
              "TF_VAR_APP_INSTALLATION_ID": "${{ secrets.TF_VAR_APP_INSTALLATION_ID }}",
              "TF_VAR_APP_PEM_FILE": "${{ secrets.TF_VAR_APP_PEM_FILE }}",
              "GITHUB_TOKEN": "${{ secrets.GITHUB_TOKEN }}"
              "TF_VAR_KEYCLOAK_CLIENT_ID": ${{ secrets.TF_VAR_KEYCLOAK_CLIENT_ID }}
              "TF_VAR_KEYCLOAK_CLIENT_SECRET": ${{ secrets.TF_VAR_KEYCLOAK_CLIENT_SECRET }}
              "TF_VAR_KEYCLOAK_URL": ${{ secrets.TF_VAR_KEYCLOAK_URL }}
            }