name: Terragrunt Apply
on:
  push:
    branches:
      - main
    paths:
      - "stack/**"
      - "!stack/onprem/**"

jobs:
  build:
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    uses: random-builds/gh-workflows/.github/workflows/terragrunt.yaml@bc7095b1ac44c87a7af59c160885fa3410fa8138
    secrets: inherit
    with:
      enable_static_checks: false
      apply: true
      terragrunt_version: 0.77.14
      terraform_version: 1.11.4
